[build]
  base = "/"
  publish = "netlify-deploy"
  command = "echo 'skip build'"

[build.environment]
  NODE_VERSION = "22"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

